// Generated by CoffeeScript 1.3.3
(function() {
  var cubes, item, list, math, num, number, opposite, race, square, writeItems, _i, _len,
    __slice = [].slice;

  number = 42;

  opposite = true;

  if (opposite) {
    number = -42;
  }

  square = function(x) {
    return x * x;
  };

  list = [1, 2, 3, 4, 5];

  math = {
    root: Math.sqrt,
    square: square,
    cube: function(x) {
      return x * square(x);
    }
  };

  race = function() {
    var runners, winner;
    winner = arguments[0], runners = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return print(winner, runners);
  };

  if (typeof elvis !== "undefined" && elvis !== null) {
    alert("I knew it!");
  }

  cubes = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      num = list[_i];
      _results.push(math.cube(num));
    }
    return _results;
  })();

  writeItems = function(item) {
    var p;
    p = document.createElement('p');
    p.innerHTML = item;
    return document.body.appendChild(p);
  };

  for (_i = 0, _len = cubes.length; _i < _len; _i++) {
    item = cubes[_i];
    writeItems(item);
  }

  window.cubes = cubes;

}).call(this);
